[package]
name = "rust_rt"
version = "0.1.0"
authors = ["niloco <niloco@umich.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
